export const defaultTheme = {
  additionalStyles: {
    Button: {
      '--n-35': 'var(--n-100)',
      '--n-10': 'var(--n-0)',
      background: 'linear-gradient(135deg, #818cf8 0%, #3b82f6 100%)',
      boxShadow: '0 4px 15px rgba(102, 126, 234, 0.4)',
      padding: '12px 28px',
      textTransform: 'uppercase',
    },
    Text: {
      h1: { color: 'transparent', background: 'linear-gradient(135deg, #818cf8 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', WebkitTextFillColor: 'transparent' },
      h2: { color: 'transparent', background: 'linear-gradient(135deg, #818cf8 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', WebkitTextFillColor: 'transparent' },
      h3: { color: 'transparent', background: 'linear-gradient(135deg, #818cf8 0%, #3b82f6 100%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', WebkitTextFillColor: 'transparent' },
      h4: {}, h5: {}, body: {}, caption: {}, warning: { color: '#facc15' },
    },
    Card: {
      background: 'linear-gradient(135deg, rgba(30, 41, 59, 0.7), rgba(15, 23, 42, 0.8))',
    },
    TextField: {
      '--p-0': '#1e293b',
    },
  },
  components: {
    AudioPlayer: {},
    Button: {
      'layout-pt-2': true, 'layout-pb-2': true, 'layout-pl-3': true, 'layout-pr-3': true,
      'border-br-12': true, 'border-bw-0': true, 'border-bs-s': true, 'color-bgc-p30': true,
      'behavior-ho-70': true, 'typography-w-400': true,
    },
    Card: { 'border-br-9': true, 'layout-p-4': true, 'color-bgc-n100': true },
    CheckBox: { container: { 'layout-dsp-iflex': true, 'layout-al-c': true }, label: { 'color-c-p30': true }, element: { 'layout-m-0': true, 'layout-mr-2': true } },
    Column: { 'layout-g-2': true },
    DateTimeInput: { container: { 'layout-w-100': true, 'layout-g-2': true }, label: { 'color-c-p30': true }, element: { 'border-br-2': true, 'border-bw-1': true } },
    Divider: {},
    Image: { all: { 'border-br-5': true, 'layout-el-cv': true, 'layout-w-100': true, 'layout-h-100': true }, avatar: { 'is-avatar': true }, header: {}, icon: {}, largeFeature: {}, mediumFeature: {}, smallFeature: {} },
    Icon: {},
    List: { 'layout-g-4': true, 'layout-p-2': true },
    Modal: { backdrop: { 'color-bbgc-p60_20': true }, element: { 'border-br-2': true, 'layout-p-4': true, 'border-bw-1': true } },
    MultipleChoice: { container: {}, label: {}, element: {} },
    Row: { 'layout-g-4': true },
    Slider: { container: {}, label: {}, element: {} },
    Tabs: { container: {}, controls: { all: {}, selected: {} }, element: {} },
    Text: {
      all: { 'layout-w-100': true, 'layout-g-2': true },
      h1: { 'typography-sz-hs': true },
      h2: { 'typography-sz-tl': true },
      h3: { 'typography-sz-tl': true },
      h4: { 'typography-sz-bl': true },
      h5: { 'typography-sz-bm': true },
      body: {}, caption: {}, warning: { 'color-c-warning': true },
    },
    TextField: { container: { 'layout-w-100': true, 'layout-g-2': true }, label: { 'color-c-p30': true }, element: { 'border-br-2': true, 'border-bw-1': true } },
    Video: { 'border-br-5': true, 'layout-el-cv': true },
  },
}
